// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddProjectToCollectionIfNeeded(arg1) {
  return window['go']['projectrelated']['ProjectManager']['AddProjectToCollectionIfNeeded'](arg1);
}

export function AnyMadeProjectFilesInFolder(arg1) {
  return window['go']['projectrelated']['ProjectManager']['AnyMadeProjectFilesInFolder'](arg1);
}

export function ChooseFolderForNewProject() {
  return window['go']['projectrelated']['ProjectManager']['ChooseFolderForNewProject']();
}

export function ChooseProject() {
  return window['go']['projectrelated']['ProjectManager']['ChooseProject']();
}

export function CreateProject(arg1, arg2, arg3, arg4) {
  return window['go']['projectrelated']['ProjectManager']['CreateProject'](arg1, arg2, arg3, arg4);
}

export function CurrentProject() {
  return window['go']['projectrelated']['ProjectManager']['CurrentProject']();
}

export function CurrentProjectAddNewRecipe(arg1, arg2) {
  return window['go']['projectrelated']['ProjectManager']['CurrentProjectAddNewRecipe'](arg1, arg2);
}

export function CurrentProjectGetItemsTypeSuggestion(arg1) {
  return window['go']['projectrelated']['ProjectManager']['CurrentProjectGetItemsTypeSuggestion'](arg1);
}

export function GetInformationToFillCreationForm(arg1) {
  return window['go']['projectrelated']['ProjectManager']['GetInformationToFillCreationForm'](arg1);
}

export function GetProjects() {
  return window['go']['projectrelated']['ProjectManager']['GetProjects']();
}

export function SaveToFile() {
  return window['go']['projectrelated']['ProjectManager']['SaveToFile']();
}

export function SetCurrentProjectByFolder(arg1) {
  return window['go']['projectrelated']['ProjectManager']['SetCurrentProjectByFolder'](arg1);
}
