// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {projectrelated} from '../models';
import {src} from '../models';

export function AddProjectToCollectionIfNeeded(arg1:string):Promise<void>;

export function AnyMadeProjectFilesInFolder(arg1:string):Promise<boolean>;

export function ChooseFolderForNewProject():Promise<string>;

export function ChooseProject():Promise<string>;

export function GetInformationToFillCreationForm(arg1:string):Promise<projectrelated.ProjectCreationInformation>;

export function SaveToFile():Promise<void>;

export function TryCreateProject(arg1:string,arg2:string,arg3:string,arg4:src.Loader):Promise<boolean>;
