// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CurrentTheme() {
  return window['go']['made']['ThemeCollection']['CurrentTheme']();
}

export function SaveToFile() {
  return window['go']['made']['ThemeCollection']['SaveToFile']();
}

export function SetCurrentTheme(arg1) {
  return window['go']['made']['ThemeCollection']['SetCurrentTheme'](arg1);
}
