// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {made} from '../models';

export function CurrentTheme():Promise<made.Theme>;

export function SaveToFile():Promise<void>;

export function SetCurrentTheme(arg1:made.Theme):Promise<void>;
