// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {themerelated} from '../models';

export function CurrentTheme():Promise<themerelated.Theme>;

export function CurrentThemeColors():Promise<{[key: string]: string}>;

export function GetAllThemesValues():Promise<Array<{[key: string]: string}>>;

export function SaveToFile():Promise<void>;

export function SetCurrentTheme(arg1:themerelated.Theme):Promise<void>;

export function ThemeFromHexToNormal(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string,arg8:string,arg9:string,arg10:string,arg11:string,arg12:string):Promise<themerelated.Theme>;

export function UpdateTheme(arg1:string,arg2:themerelated.Theme):Promise<string>;
