// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CurrentTheme() {
  return window['go']['themerelated']['ThemeCollection']['CurrentTheme']();
}

export function CurrentThemeColors() {
  return window['go']['themerelated']['ThemeCollection']['CurrentThemeColors']();
}

export function GetAllThemesValues() {
  return window['go']['themerelated']['ThemeCollection']['GetAllThemesValues']();
}

export function GetHexDefaultDark() {
  return window['go']['themerelated']['ThemeCollection']['GetHexDefaultDark']();
}

export function SaveToFile() {
  return window['go']['themerelated']['ThemeCollection']['SaveToFile']();
}

export function SetCurrentTheme(arg1) {
  return window['go']['themerelated']['ThemeCollection']['SetCurrentTheme'](arg1);
}

export function ThemeFromHexTheme(arg1) {
  return window['go']['themerelated']['ThemeCollection']['ThemeFromHexTheme'](arg1);
}

export function UpdateTheme(arg1, arg2) {
  return window['go']['themerelated']['ThemeCollection']['UpdateTheme'](arg1, arg2);
}
