// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {themerelated} from '../models';

export function CurrentTheme():Promise<themerelated.Theme>;

export function CurrentThemeColors():Promise<{[key: string]: string}>;

export function SaveToFile():Promise<void>;

export function SetCurrentTheme(arg1:themerelated.Theme):Promise<void>;
